#!/bin/bash

COMANDO=$1

function echoerr {
  $BINDIR/GrabarBitacora DetenerProceso "$1" ERR
}

if [ ! -f $BINDIR/$COMANDO ]; then
  echoerr "No existe el comando $COMANDO"
  exit 1
fi 

if ! ps | grep $COMANDO >/dev/null 2>&1; then
  echoerr "El comando no se encuentra en ejecución."
  exit 1
fi

PID=`pidof $COMANDO`

if ! kill $PID; then
  echoerr "No se pudo detener el proceso."
  exit 1
fi
