#!/bin/bash

echo ""
echo "CIPAL: Generando sorteo."
echo ""

IFS='
'

# Cantidad de cambios que se va a ejecutar en el vector
cambios=5000
RANGO=168

function echoerr {
  echo $1 1>&2
}

# Se crea un arreglo con los 168 numeros
for i in $(seq 1 $RANGO); do numeros[$i]=$i; done

function cambiar_indices {
  aux=${numeros[$1]}
  numeros[$1]=${numeros[$2]}
  numeros[$2]=$aux
}

# Se cambian aleatoriamente los numeros en el arreglo
for i in $(seq 1 $cambios)
do
  let "index_a=($RANDOM%$RANGO)+1"
  let "index_b=($RANDOM%$RANGO)+1"
  cambiar_indices $index_a $index_b
done

# Localizar proxima fecha de adjudicacion
while read -r fecha
do
	fecha=$(echo $fecha | cut -f1 -d';')
	fecha=$(echo $fecha | sed 's-\([0-3][0-9]\)/\([0-1][0-9]\)/\([0-9]\{4\}\)-\3\2\1-')
    if [ `date +%Y%m%d` -lt $fecha ]; then
		fecha_adj=$fecha
		break
	fi
done < $MAEDIR/FechasAdj.csv

# Archivo de entrada de datos y ruta de salida
entrada="$MAEDIR/FechasAdj.csv"
ruta_salida="$PROCDIR/sorteos"

if [ ! -f $entrada ]; then
    entrada=$entrada+".xls"
fi

ultima_fecha=$fecha_adj

# Si ya existen sorteos con ese id se aumenta el numero de id
count=1
while ls "$ruta_salida" | grep "^$count\_" > /dev/null
do
    let count++
done
salida="$ruta_salida/$count"_"$ultima_fecha.csv"

# Se guarda el sorteo en el archivo de salida y se logea.
$BINDIR/GrabarBitacora GenerarSorteo "Inicio de Sorteo id: $count" INFO
for i in $(seq 1 $RANGO)
do
    echo "$i;${numeros[$i]}" >> $salida
    $BINDIR/GrabarBitacora -s GenerarSorteo "Numero de orden $i le corresponde el numero de sorteo ${numeros[$i]}" INFO
done
$BINDIR/GrabarBitacora GenerarSorteo "Fin de Sorteo id: $count" INFO

echo "Sorteo generado"
