#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Modo de uso:"
  echo "GrabarBitacora <comando> <mensaje> [<INFO|WAR|ERR>]"
  exit 1
fi

USUARIO=`whoami`
FECHAYHORA=`date`
COMANDO=$1
TIPOMSJ=$3
MENSAJE=$2

if ! echo $TIPOMSJ | grep -e "^\(INFO\|WAR\|ERR\)$" >/dev/null 2>&1; then
  TIPOMSJ=INFO
fi

ARCHIVO="$LOGDIR/$COMANDO.log"

if [ -f $ARCHIVO ]; then
  LINEAS=`cat $ARCHIVO | wc -l`
else
  LINEAS=0
fi

if [ $LINEAS -ge $LOGSIZE ]; then
  indice_inicial=`echo "$LINEAS - $LOGSIZE + 2" | bc`
  sed -i -n "$indice_inicial,$ p" $ARCHIVO
fi

echo "$USUARIO|$FECHAYHORA|$COMANDO|$TIPOMSJ|$MENSAJE" >> $ARCHIVO
