#!/bin/bash

function modo_de_uso {
  echo "Modo de uso:"
  echo "MostrarBitacora <comando> [filtro]"
}

function echoerr {
  $BINDIR/GrabarBitacora MostrarBitacora "$1" ERR
  exit 1
}

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  modo_de_uso
  exit 1
fi

if [ $# -eq 2 ]; then
  FILTRO=$2
fi

COMANDO=$1

if [ ! -r "$LOGDIR/$COMANDO.log" ]; then
  echoerr "No existe log $COMANDO.log en LOGDIR."
  exit 1
fi

if [ -v FILTRO ]; then
  cat "$LOGDIR/$COMANDO.log" | grep "$FILTRO"
else
  cat "$LOGDIR/$COMANDO.log"
fi
